//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiaUtilities.Languages {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiaUtilities.Languages.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil.
        /// </summary>
        internal static string ALARM_CONFIG_COIL_TYPE_COIL {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_COIL_TYPE_COIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ignore.
        /// </summary>
        internal static string ALARM_CONFIG_COIL_TYPE_NONE {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_COIL_TYPE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset.
        /// </summary>
        internal static string ALARM_CONFIG_COIL_TYPE_RESET {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_COIL_TYPE_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set.
        /// </summary>
        internal static string ALARM_CONFIG_COIL_TYPE_SET {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_COIL_TYPE_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 1 Type.
        /// </summary>
        internal static string ALARM_CONFIG_COIL1_TYPE {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_COIL1_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 2 Type.
        /// </summary>
        internal static string ALARM_CONFIG_COIL2_TYPE {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_COIL2_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Field default Values.
        /// </summary>
        internal static string ALARM_CONFIG_DEFAULTS {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_DEFAULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 1.
        /// </summary>
        internal static string ALARM_CONFIG_DEFAULTS_COIL1 {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_DEFAULTS_COIL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 2.
        /// </summary>
        internal static string ALARM_CONFIG_DEFAULTS_COIL2 {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_DEFAULTS_COIL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timer.
        /// </summary>
        internal static string ALARM_CONFIG_DEFAULTS_TIMER {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_DEFAULTS_TIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FC.
        /// </summary>
        internal static string ALARM_CONFIG_FC {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generation.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Anti-Slip.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_ANTI_SLIP {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_ANTI_SLIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Group Size.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_ANTI_SLIP_AMOUNT {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_ANTI_SLIP_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generate Empty.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_ANTI_SLIP_GEN_EMPTY {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_ANTI_SLIP_GEN_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generation Empty.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_EMPTY {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm Address.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_EMPTY_ALARM_ADDRESS {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_EMPTY_ALARM_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generate in anti-slip.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_EMPTY_ANTI_SLIP {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_EMPTY_ANTI_SLIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Num. at end.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_EMPTY_NUM {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_EMPTY_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timer.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_EMPTY_TIMER {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_EMPTY_TIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Address.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_EMPTY_TIMER_ADDRESS {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_EMPTY_TIMER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_EMPTY_TIMER_TYPE {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_EMPTY_TIMER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Time.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_EMPTY_TIMER_VALUE {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_EMPTY_TIMER_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Format.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_FORMAT {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Skip after each group.
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_SKIP {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Starting Num..
        /// </summary>
        internal static string ALARM_CONFIG_GENERATION_START_NUM {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GENERATION_START_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grouping type.
        /// </summary>
        internal static string ALARM_CONFIG_GROUPING_TYPE {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GROUPING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GroupPerSegment.
        /// </summary>
        internal static string ALARM_CONFIG_GROUPING_TYPE_GROUP {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GROUPING_TYPE_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OnePerSegment.
        /// </summary>
        internal static string ALARM_CONFIG_GROUPING_TYPE_ONE {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_GROUPING_TYPE_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Partition type.
        /// </summary>
        internal static string ALARM_CONFIG_PARTITION_TYPE {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_PARTITION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AlarmType.
        /// </summary>
        internal static string ALARM_CONFIG_PARTITION_TYPE_ALARM_TYPE {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_PARTITION_TYPE_ALARM_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Device.
        /// </summary>
        internal static string ALARM_CONFIG_PARTITION_TYPE_DEVICE {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_PARTITION_TYPE_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Field Prefixes.
        /// </summary>
        internal static string ALARM_CONFIG_PREFIX {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm Address.
        /// </summary>
        internal static string ALARM_CONFIG_PREFIX_ALARM {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_PREFIX_ALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 1 Address.
        /// </summary>
        internal static string ALARM_CONFIG_PREFIX_COIL1 {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_PREFIX_COIL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 2 Address.
        /// </summary>
        internal static string ALARM_CONFIG_PREFIX_COIL2 {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_PREFIX_COIL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timer Address.
        /// </summary>
        internal static string ALARM_CONFIG_PREFIX_TIMER {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_PREFIX_TIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Segment Names.
        /// </summary>
        internal static string ALARM_CONFIG_SEGMENT_NAME {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_SEGMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Groupped.
        /// </summary>
        internal static string ALARM_CONFIG_SEGMENT_NAME_GROUP_EACH {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_SEGMENT_NAME_GROUP_EACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Groupped(Empty).
        /// </summary>
        internal static string ALARM_CONFIG_SEGMENT_NAME_GROUP_EACH_EMPTY {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_SEGMENT_NAME_GROUP_EACH_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a One each.
        /// </summary>
        internal static string ALARM_CONFIG_SEGMENT_NAME_ONE_EACH {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_SEGMENT_NAME_ONE_EACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a One each(Empty).
        /// </summary>
        internal static string ALARM_CONFIG_SEGMENT_NAME_ONE_EACH_EMPTY {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_SEGMENT_NAME_ONE_EACH_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm Text List.
        /// </summary>
        internal static string ALARM_CONFIG_TEXT_LIST {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_TEXT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Empty.
        /// </summary>
        internal static string ALARM_CONFIG_TEXT_LIST_EMPTY {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_TEXT_LIST_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Full.
        /// </summary>
        internal static string ALARM_CONFIG_TEXT_LIST_FULL {
            get {
                return ResourceManager.GetString("ALARM_CONFIG_TEXT_LIST_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm Variable.
        /// </summary>
        internal static string ALARM_DATA_ALM_VARIABLE {
            get {
                return ResourceManager.GetString("ALARM_DATA_ALM_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil1 Address.
        /// </summary>
        internal static string ALARM_DATA_COIL1_ADDRESS {
            get {
                return ResourceManager.GetString("ALARM_DATA_COIL1_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string ALARM_DATA_COIL1_TYPE {
            get {
                return ResourceManager.GetString("ALARM_DATA_COIL1_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil2 Address.
        /// </summary>
        internal static string ALARM_DATA_COIL2_ADDRESS {
            get {
                return ResourceManager.GetString("ALARM_DATA_COIL2_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string ALARM_DATA_COIL2_TYPE {
            get {
                return ResourceManager.GetString("ALARM_DATA_COIL2_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Description.
        /// </summary>
        internal static string ALARM_DATA_DESCRIPTION {
            get {
                return ResourceManager.GetString("ALARM_DATA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enable.
        /// </summary>
        internal static string ALARM_DATA_ENABLE {
            get {
                return ResourceManager.GetString("ALARM_DATA_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timer Address.
        /// </summary>
        internal static string ALARM_DATA_TIMER_ADDRESS {
            get {
                return ResourceManager.GetString("ALARM_DATA_TIMER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string ALARM_DATA_TIMER_TYPE {
            get {
                return ResourceManager.GetString("ALARM_DATA_TIMER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Time.
        /// </summary>
        internal static string ALARM_DATA_TIMER_VALUE {
            get {
                return ResourceManager.GetString("ALARM_DATA_TIMER_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarms generator.
        /// </summary>
        internal static string ALARM_GEN_FORM {
            get {
                return ResourceManager.GetString("ALARM_GEN_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Description.
        /// </summary>
        internal static string DEVICE_DATA_DESCRIPTION {
            get {
                return ResourceManager.GetString("DEVICE_DATA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        internal static string DEVICE_DATA_NAME {
            get {
                return ResourceManager.GetString("DEVICE_DATA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Address.
        /// </summary>
        internal static string GENERICS_ADDRESS {
            get {
                return ResourceManager.GetString("GENERICS_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File.
        /// </summary>
        internal static string GENERICS_FILE {
            get {
                return ResourceManager.GetString("GENERICS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load.
        /// </summary>
        internal static string GENERICS_LOAD {
            get {
                return ResourceManager.GetString("GENERICS_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        internal static string GENERICS_NAME {
            get {
                return ResourceManager.GetString("GENERICS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Number.
        /// </summary>
        internal static string GENERICS_NUMBER {
            get {
                return ResourceManager.GetString("GENERICS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        internal static string GENERICS_SAVE {
            get {
                return ResourceManager.GetString("GENERICS_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SaveAs.
        /// </summary>
        internal static string GENERICS_SAVE_AS {
            get {
                return ResourceManager.GetString("GENERICS_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string GENERICS_TYPE {
            get {
                return ResourceManager.GetString("GENERICS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value.
        /// </summary>
        internal static string GENERICS_VALUE {
            get {
                return ResourceManager.GetString("GENERICS_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Find.
        /// </summary>
        internal static string GRID_FIND_FIND_BUTTON {
            get {
                return ResourceManager.GetString("GRID_FIND_FIND_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grid - Find and Replace.
        /// </summary>
        internal static string GRID_FIND_FORM_NAME {
            get {
                return ResourceManager.GetString("GRID_FIND_FORM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Match Case.
        /// </summary>
        internal static string GRID_FIND_MATCH_CASE_CHECKBOX {
            get {
                return ResourceManager.GetString("GRID_FIND_MATCH_CASE_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ReplaceAll.
        /// </summary>
        internal static string GRID_FIND_REPLACE_ALL_BUTTON {
            get {
                return ResourceManager.GetString("GRID_FIND_REPLACE_ALL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search completed. Replaced {count} values..
        /// </summary>
        internal static string GRID_FIND_REPLACE_ALL_COMPLETED {
            get {
                return ResourceManager.GetString("GRID_FIND_REPLACE_ALL_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Replace.
        /// </summary>
        internal static string GRID_FIND_REPLACE_BUTTON {
            get {
                return ResourceManager.GetString("GRID_FIND_REPLACE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search completed.
        /// </summary>
        internal static string GRID_FIND_SEARCH_COMPLETED {
            get {
                return ResourceManager.GetString("GRID_FIND_SEARCH_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grid Preferences.
        /// </summary>
        internal static string GRID_PREFERENCES {
            get {
                return ResourceManager.GetString("GRID_PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Drag triangle.
        /// </summary>
        internal static string GRID_PREFERENCES_DRAG_TRIANGLE_COLOR {
            get {
                return ResourceManager.GetString("GRID_PREFERENCES_DRAG_TRIANGLE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dragged cell background.
        /// </summary>
        internal static string GRID_PREFERENCES_DRAGGED_CELL_BACK {
            get {
                return ResourceManager.GetString("GRID_PREFERENCES_DRAGGED_CELL_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preview.
        /// </summary>
        internal static string GRID_PREFERENCES_PREVIEW_FORE {
            get {
                return ResourceManager.GetString("GRID_PREFERENCES_PREVIEW_FORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selected cell border.
        /// </summary>
        internal static string GRID_PREFERENCES_SELECTED_CELL_BORDER {
            get {
                return ResourceManager.GetString("GRID_PREFERENCES_SELECTED_CELL_BORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Format Code.
        /// </summary>
        internal static string GRID_SCRIPT_AUTO_FORMAT {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_AUTO_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Execute on all lines.
        /// </summary>
        internal static string GRID_SCRIPT_EXECUTE_ALL {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_EXECUTE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Execute Debug.
        /// </summary>
        internal static string GRID_SCRIPT_EXECUTE_DEBUG {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_EXECUTE_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Execute on selected line.
        /// </summary>
        internal static string GRID_SCRIPT_EXECUTE_ONE_LINE {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_EXECUTE_ONE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Javascript Expression.
        /// </summary>
        internal static string GRID_SCRIPT_JS_EXPRESSION {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_JS_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a JSON Context.
        /// </summary>
        internal static string GRID_SCRIPT_JSON_CONTEXT {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_JSON_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open Javascript executed.
        /// </summary>
        internal static string GRID_SCRIPT_OPEN_JAVASCRIPT_CONTEXT {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_OPEN_JAVASCRIPT_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Variables: .
        /// </summary>
        internal static string GRID_SCRIPT_VARIABLES {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_VARIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grouping Type.
        /// </summary>
        internal static string IO_CONFIG_GROUPING_TYPE {
            get {
                return ResourceManager.GetString("IO_CONFIG_GROUPING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GroupEachBit.
        /// </summary>
        internal static string IO_CONFIG_GROUPING_TYPE_BIT {
            get {
                return ResourceManager.GetString("IO_CONFIG_GROUPING_TYPE_BIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GroupEachByte.
        /// </summary>
        internal static string IO_CONFIG_GROUPING_TYPE_BYTE {
            get {
                return ResourceManager.GetString("IO_CONFIG_GROUPING_TYPE_BYTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Memory Type.
        /// </summary>
        internal static string IO_CONFIG_MEMORY_TYPE {
            get {
                return ResourceManager.GetString("IO_CONFIG_MEMORY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DB.
        /// </summary>
        internal static string IO_CONFIG_MEMORY_TYPE_DB {
            get {
                return ResourceManager.GetString("IO_CONFIG_MEMORY_TYPE_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merker.
        /// </summary>
        internal static string IO_CONFIG_MEMORY_TYPE_MERKER {
            get {
                return ResourceManager.GetString("IO_CONFIG_MEMORY_TYPE_MERKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Address.
        /// </summary>
        internal static string IO_DATA_ADDRESS {
            get {
                return ResourceManager.GetString("IO_DATA_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Comment.
        /// </summary>
        internal static string IO_DATA_COMMENT {
            get {
                return ResourceManager.GetString("IO_DATA_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IO Tag.
        /// </summary>
        internal static string IO_DATA_IO_NAME {
            get {
                return ResourceManager.GetString("IO_DATA_IO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merker Address.
        /// </summary>
        internal static string IO_DATA_MERKER_ADDRESS {
            get {
                return ResourceManager.GetString("IO_DATA_MERKER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Negated.
        /// </summary>
        internal static string IO_DATA_NEGATED {
            get {
                return ResourceManager.GetString("IO_DATA_NEGATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Variable.
        /// </summary>
        internal static string IO_DATA_VARIABLE {
            get {
                return ResourceManager.GetString("IO_DATA_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alias DB.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_DB {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Genera Defined variables.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_DB_GENERATED_DEFINED_VARIABLES {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_DB_GENERATED_DEFINED_VARIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Default Input value.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_DB_IN_DEFAULT {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_DB_IN_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Default Output value.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_DB_OUT_DEFAULT {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_DB_OUT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alias Table.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_TABLE {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Input Variable.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_TABLE_INPUT_VARIABLE {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_TABLE_INPUT_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New every n° bit.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_TABLE_NEW_EVERY {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_TABLE_NEW_EVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Output Variable.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_TABLE_OUTPUT_VARIABLE {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_TABLE_OUTPUT_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Default Value.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_TABLE_VARIABLE_DEFAULT {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_TABLE_VARIABLE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start Address.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_TABLE_VARIABLE_START_ADDRESS {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_TABLE_VARIABLE_START_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alias FC.
        /// </summary>
        internal static string IO_GEN_CONFIG_FC {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IN/OUT Table.
        /// </summary>
        internal static string IO_GEN_CONFIG_IO_TABLE {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_IO_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Default tag name.
        /// </summary>
        internal static string IO_GEN_CONFIG_IO_TABLE_DEFAULT_NAME {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_IO_TABLE_DEFAULT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New every n° bit.
        /// </summary>
        internal static string IO_GEN_CONFIG_IO_TABLE_NEW_EVERY {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_IO_TABLE_NEW_EVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Segment Name.
        /// </summary>
        internal static string IO_GEN_CONFIG_SEGMENT {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Division per bit.
        /// </summary>
        internal static string IO_GEN_CONFIG_SEGMENT_BIT_DIVISION {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_SEGMENT_BIT_DIVISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Division per byte.
        /// </summary>
        internal static string IO_GEN_CONFIG_SEGMENT_BYTE_DIVISION {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_SEGMENT_BYTE_DIVISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import/Export.
        /// </summary>
        internal static string IO_GEN_FORM_IMPEXP {
            get {
                return ResourceManager.GetString("IO_GEN_FORM_IMPEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export XML.
        /// </summary>
        internal static string IO_GEN_FORM_IMPEXP_EXPORT_XML {
            get {
                return ResourceManager.GetString("IO_GEN_FORM_IMPEXP_EXPORT_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import Excel.
        /// </summary>
        internal static string IO_GEN_FORM_IMPEXP_IMPORT_EXCEL {
            get {
                return ResourceManager.GetString("IO_GEN_FORM_IMPEXP_IMPORT_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import Suggestions From DB/Tags.
        /// </summary>
        internal static string IO_GEN_FORM_IMPEXP_IMPORT_SUGGESTION {
            get {
                return ResourceManager.GetString("IO_GEN_FORM_IMPEXP_IMPORT_SUGGESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Input/Output alias generator. Project file: {file_path}.
        /// </summary>
        internal static string IO_GEN_FORM_NAME {
            get {
                return ResourceManager.GetString("IO_GEN_FORM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prompt.
        /// </summary>
        internal static string IO_SUGGESTION_DATA_VALUE {
            get {
                return ResourceManager.GetString("IO_SUGGESTION_DATA_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tia Utilities.
        /// </summary>
        internal static string MAIN_FORM {
            get {
                return ResourceManager.GetString("MAIN_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language.
        /// </summary>
        internal static string MAIN_FORM_LANGUAGE {
            get {
                return ResourceManager.GetString("MAIN_FORM_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TIA Portal Version.
        /// </summary>
        internal static string MAIN_FORM_TIA_VERSION {
            get {
                return ResourceManager.GetString("MAIN_FORM_TIA_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm Generator.
        /// </summary>
        internal static string MAIN_FORM_TOP_ALARM_GENERATOR {
            get {
                return ResourceManager.GetString("MAIN_FORM_TOP_ALARM_GENERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DB Duplication.
        /// </summary>
        internal static string MAIN_FORM_TOP_DB_DUPLICATION {
            get {
                return ResourceManager.GetString("MAIN_FORM_TOP_DB_DUPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AutoSave (s).
        /// </summary>
        internal static string MAIN_FORM_TOP_FILE_AUTO_SAVE {
            get {
                return ResourceManager.GetString("MAIN_FORM_TOP_FILE_AUTO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alias Generator.
        /// </summary>
        internal static string MAIN_FORM_TOP_IO_GENERATION {
            get {
                return ResourceManager.GetString("MAIN_FORM_TOP_IO_GENERATION", resourceCulture);
            }
        }
    }
}
