//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiaUtilities.Languages {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiaUtilities.Languages.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarms generator. Project file: {file_path}.
        /// </summary>
        internal static string ALARM_GEN_FORM {
            get {
                return ResourceManager.GetString("ALARM_GEN_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Group Size.
        /// </summary>
        internal static string ALARM_SETTINGS__GENERATION_ANTI_SLIP_AMOUNT {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS__GENERATION_ANTI_SLIP_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm number format.
        /// </summary>
        internal static string ALARM_SETTINGS_ALARM_NUM_PLACEHOLDER_FORMAT {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_ALARM_NUM_PLACEHOLDER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a String format for all alarm number placeholders. Please follow String.Format C# guide..
        /// </summary>
        internal static string ALARM_SETTINGS_ALARM_NUM_PLACEHOLDER_FORMAT_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_ALARM_NUM_PLACEHOLDER_FORMAT_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil.
        /// </summary>
        internal static string ALARM_SETTINGS_COIL_TYPE_COIL {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_COIL_TYPE_COIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a N-Coil.
        /// </summary>
        internal static string ALARM_SETTINGS_COIL_TYPE_NCOIL {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_COIL_TYPE_NCOIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ignore.
        /// </summary>
        internal static string ALARM_SETTINGS_COIL_TYPE_NONE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_COIL_TYPE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset.
        /// </summary>
        internal static string ALARM_SETTINGS_COIL_TYPE_RESET {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_COIL_TYPE_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set.
        /// </summary>
        internal static string ALARM_SETTINGS_COIL_TYPE_SET {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_COIL_TYPE_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit Template.
        /// </summary>
        internal static string ALARM_SETTINGS_EDIT_TEMPLATE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_EDIT_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enablings.
        /// </summary>
        internal static string ALARM_SETTINGS_ENABLE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Custom variable.
        /// </summary>
        internal static string ALARM_SETTINGS_ENABLE_CUSTOM_VAR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_ENABLE_CUSTOM_VAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enable custom variable inside templates..
        /// </summary>
        internal static string ALARM_SETTINGS_ENABLE_CUSTOM_VAR_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_ENABLE_CUSTOM_VAR_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timer.
        /// </summary>
        internal static string ALARM_SETTINGS_ENABLE_TIMER {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_ENABLE_TIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enable timer inside templates..
        /// </summary>
        internal static string ALARM_SETTINGS_ENABLE_TIMER_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_ENABLE_TIMER_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FC.
        /// </summary>
        internal static string ALARM_SETTINGS_FC {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grouping type.
        /// </summary>
        internal static string ALARM_SETTINGS_GROUPING_TYPE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_GROUPING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Groupped.
        /// </summary>
        internal static string ALARM_SETTINGS_GROUPING_TYPE_GROUP {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_GROUPING_TYPE_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Single.
        /// </summary>
        internal static string ALARM_SETTINGS_GROUPING_TYPE_ONE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_GROUPING_TYPE_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm name.
        /// </summary>
        internal static string ALARM_SETTINGS_HMI_ITEM_NAME {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_HMI_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value to be used inside siemens WinCC &quot;Name&quot; column..
        /// </summary>
        internal static string ALARM_SETTINGS_HMI_ITEM_NAME_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_HMI_ITEM_NAME_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm text.
        /// </summary>
        internal static string ALARM_SETTINGS_HMI_ITEM_TEXT {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_HMI_ITEM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value to be used inside siemens WinCC &quot;Alarm Text&quot; column..
        /// </summary>
        internal static string ALARM_SETTINGS_HMI_ITEM_TEXT_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_HMI_ITEM_TEXT_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        internal static string ALARM_SETTINGS_HMI_NAME {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_HMI_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trigger tag.
        /// </summary>
        internal static string ALARM_SETTINGS_HMI_TRIGGER_TAG {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_HMI_TRIGGER_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value to be used inside siemens WinCC &quot;Trigger Tag&quot; column..
        /// </summary>
        internal static string ALARM_SETTINGS_HMI_TRIGGER_TAG_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_HMI_TRIGGER_TAG_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Word array as trigger (Unified).
        /// </summary>
        internal static string ALARM_SETTINGS_HMI_USE_WORD_ARRAY {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_HMI_USE_WORD_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Define if the &quot;Trigger Tag&quot; should use single element of the Array[*] of word inside WinCC (e.g. HmiAlm[0], increasing &quot;Trigger Bit&quot; up to 15) instead of the full tag (Increasing &quot;Trigger Bit&quot; indefinately). Used for WinCC Unified panels..
        /// </summary>
        internal static string ALARM_SETTINGS_HMI_USE_WORD_ARRAY_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_HMI_USE_WORD_ARRAY_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Partition type.
        /// </summary>
        internal static string ALARM_SETTINGS_PARTITION_TYPE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_PARTITION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AlarmType.
        /// </summary>
        internal static string ALARM_SETTINGS_PARTITION_TYPE_ALARM_TYPE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_PARTITION_TYPE_ALARM_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Device.
        /// </summary>
        internal static string ALARM_SETTINGS_PARTITION_TYPE_DEVICE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_PARTITION_TYPE_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Field Prefixes.
        /// </summary>
        internal static string ALARM_SETTINGS_PREFIX {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm Address.
        /// </summary>
        internal static string ALARM_SETTINGS_PREFIX_ALARM {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_PREFIX_ALARM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 1 Address.
        /// </summary>
        internal static string ALARM_SETTINGS_PREFIX_COIL1 {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_PREFIX_COIL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 2 Address.
        /// </summary>
        internal static string ALARM_SETTINGS_PREFIX_COIL2 {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_PREFIX_COIL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timer Address.
        /// </summary>
        internal static string ALARM_SETTINGS_PREFIX_TIMER {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_PREFIX_TIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm numbers.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_ALARM_NUMS {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_ALARM_NUMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Starting at.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_ALARM_NUMS_START {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_ALARM_NUMS_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm number offset to be start at when generating alarms. Valid both for UDT and FC..
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_ALARM_NUMS_START_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_ALARM_NUMS_START_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Total.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_ALARM_NUMS_TOTAL {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_ALARM_NUMS_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Total number of alarms to be generated inside UDT. Generated quantity inside FC block depends on templates and other settings..
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_ALARM_NUMS_TOTAL_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_ALARM_NUMS_TOTAL_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grouping type.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_GROUPING_TYPE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_GROUPING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Define if every fc segment contains a complete template or an individual alarm.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_GROUPING_TYPE_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_GROUPING_TYPE_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Default Alarm Class.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_HMI_DEFAULT_ALARM_CLASS {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_HMI_DEFAULT_ALARM_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Define default value for column &quot;Class&quot; in WinCC inside templates..
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_HMI_DEFAULT_ALARM_CLASS_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_HMI_DEFAULT_ALARM_CLASS_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start ID.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_HMI_START_ID {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_HMI_START_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Defines start number for column &quot;ID&quot; in WinCC..
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_HMI_START_ID_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_HMI_START_ID_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Placeholders.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_PLACEHOLDERS {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_PLACEHOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Allows to add custom placeholders to use during .xml file generation. Create a simple JSON Object and each value will be treated as placeholder. {YOUR_PLACEHOLDER_NAME_HERE}.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_PLACEHOLDERS_DESC {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_PLACEHOLDERS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Segment Names.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SEGMENT_NAME {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SEGMENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Groupped.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SEGMENT_NAME_GROUP_EACH {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SEGMENT_NAME_GROUP_EACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Segment name inside the FC block for the GroupingType groupped..
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SEGMENT_NAME_GROUP_EACH_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SEGMENT_NAME_GROUP_EACH_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Groupped (Spare).
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SEGMENT_NAME_GROUP_EACH_SPARE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SEGMENT_NAME_GROUP_EACH_SPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a One each.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SEGMENT_NAME_ONE_EACH {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SEGMENT_NAME_ONE_EACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Segment name inside the FC block for the GroupingType single..
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SEGMENT_NAME_ONE_EACH_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SEGMENT_NAME_ONE_EACH_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a One each (Spare).
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SEGMENT_NAME_ONE_EACH_SPARE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SEGMENT_NAME_ONE_EACH_SPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Spare alarms.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SPARE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm Address.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SPARE_ADDRESS {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SPARE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Anti-Slip.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SPARE_ANTI_SLIP {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SPARE_ANTI_SLIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Defines the quantity of alarms for each template to avoid slipping. If the alarm quantity inside a template is lower than this, it will skip alarms (Or generate spare if enabled). Set 0 to disable..
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SPARE_ANTI_SLIP_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SPARE_ANTI_SLIP_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generate Empty for Anti-Slip.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SPARE_ANTI_SLIP_GEN_EMPTY {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SPARE_ANTI_SLIP_GEN_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Num. at end.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SPARE_EMPTY_NUM_AT_END {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SPARE_EMPTY_NUM_AT_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantity of spare alarm to generate at the end of FC block..
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SPARE_EMPTY_NUM_AT_END_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SPARE_EMPTY_NUM_AT_END_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantity after each group.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SPARE_GROUP_SKIP {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SPARE_GROUP_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantity of spare alarm to generate at the end of each template..
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_SPARE_GROUP_SKIP_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_SPARE_GROUP_SKIP_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Templates default.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_TEMPLATE_DEFAULTS {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_TEMPLATE_DEFAULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 1 Defaults.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_TEMPLATE_DEFAULTS_COIL1 {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_TEMPLATE_DEFAULTS_COIL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil 2 Defaults.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_TEMPLATE_DEFAULTS_COIL2 {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_TEMPLATE_DEFAULTS_COIL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Custom variable Defaults.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_TEMPLATE_DEFAULTS_CUSTOM_VAR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_TEMPLATE_DEFAULTS_CUSTOM_VAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timer Defaults.
        /// </summary>
        internal static string ALARM_SETTINGS_TAB_TEMPLATE_DEFAULTS_TIMER {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TAB_TEMPLATE_DEFAULTS_TIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Standalone Alarms.
        /// </summary>
        internal static string ALARM_SETTINGS_TEMPLATE_STANDALONE_ALARMS {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TEMPLATE_STANDALONE_ALARMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Allows to ignore all the default values from the alarm setup. Useful for generating standalone alarms that are not linked to a device..
        /// </summary>
        internal static string ALARM_SETTINGS_TEMPLATE_STANDALONE_ALARMS_DESC {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TEMPLATE_STANDALONE_ALARMS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm Text List.
        /// </summary>
        internal static string ALARM_SETTINGS_TEXT_LIST {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TEXT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Empty.
        /// </summary>
        internal static string ALARM_SETTINGS_TEXT_LIST_EMPTY {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TEXT_LIST_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Full.
        /// </summary>
        internal static string ALARM_SETTINGS_TEXT_LIST_FULL {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_TEXT_LIST_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UDT.
        /// </summary>
        internal static string ALARM_SETTINGS_UDT {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_UDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UDT Alarm variable.
        /// </summary>
        internal static string ALARM_SETTINGS_UDT_ALARM_VARIABLE {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_UDT_ALARM_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm comment.
        /// </summary>
        internal static string ALARM_SETTINGS_UDT_ALARM_VARIABLE_COMMENT {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_UDT_ALARM_VARIABLE_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm name.
        /// </summary>
        internal static string ALARM_SETTINGS_UDT_ALARM_VARIABLE_NAME {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_UDT_ALARM_VARIABLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SPARE alarm comment.
        /// </summary>
        internal static string ALARM_SETTINGS_UDT_ALARM_VARIABLE_SPARE_COMMENT {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_UDT_ALARM_VARIABLE_SPARE_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generated UDT given name.
        /// </summary>
        internal static string ALARM_SETTINGS_UDT_DESCR {
            get {
                return ResourceManager.GetString("ALARM_SETTINGS_UDT_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Negated.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_ALM_NEGATED {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_ALM_NEGATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm Variable.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_ALM_VARIABLE {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_ALM_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil1 Address.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_COIL1_ADDRESS {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_COIL1_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_COIL1_TYPE {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_COIL1_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coil2 Address.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_COIL2_ADDRESS {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_COIL2_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_COIL2_TYPE {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_COIL2_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Custom Variable.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_CUSTOM_VAR_ADDR {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_CUSTOM_VAR_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_CUSTOM_VAR_VALUE {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_CUSTOM_VAR_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm Text.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_DESCRIPTION {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enable.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_ENABLE {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hmi Class.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_HMI_CLASS {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_HMI_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hmi Parameters.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_HMI_PARAMETERS {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_HMI_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a HMI Alarm Text.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_HMI_TEXT {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_HMI_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timer Address.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_TIMER_ADDRESS {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_TIMER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_TIMER_TYPE {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_TIMER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Time.
        /// </summary>
        internal static string ALARM_TEMPLATE_DATA_TIMER_VALUE {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_DATA_TIMER_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Template Configurator.
        /// </summary>
        internal static string ALARM_TEMPLATE_FORM {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alignment.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_ALIGNMENT {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_ALIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Display type.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Binary.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_BINARY {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_BINARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Decimal.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_DECIMAL {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_DECIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Float.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_FLOATING_POINT {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_FLOATING_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hexadecimal.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_HEX {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Octal.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_OCTAL {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_OCTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Text.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_TEXT {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Text List.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_TEXT_LIST {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_DISPLAY_TYPE_TEXT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Length.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_LENGTH {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Decimals.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_PRECISION {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_PRECISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tag.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_TAG {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Text list.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_TEXT_LIST {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_TEXT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Zero Padding.
        /// </summary>
        internal static string ALARM_TEMPLATE_HMI_PARAM_ZERO_PADDING {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_HMI_PARAM_ZERO_PADDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select Template.
        /// </summary>
        internal static string ALARM_TEMPLATE_SELECT_TEMPLATE {
            get {
                return ResourceManager.GetString("ALARM_TEMPLATE_SELECT_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save actual configuration as default.
        /// </summary>
        internal static string CONFIG_LINE_SAVE_DEFAULT_TOOLTIP {
            get {
                return ResourceManager.GetString("CONFIG_LINE_SAVE_DEFAULT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete confirmation.
        /// </summary>
        internal static string CONFIRM_DELETE_DIALOG_CAPTION {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_DIALOG_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to delete {delete_item}?.
        /// </summary>
        internal static string CONFIRM_DELETE_DIALOG_TEXT {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_DIALOG_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Description.
        /// </summary>
        internal static string DEVICE_DATA_DESCRIPTION {
            get {
                return ResourceManager.GetString("DEVICE_DATA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        internal static string DEVICE_DATA_NAME {
            get {
                return ResourceManager.GetString("DEVICE_DATA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Placeholders.
        /// </summary>
        internal static string DEVICE_DATA_PLACEHOLDERS {
            get {
                return ResourceManager.GetString("DEVICE_DATA_PLACEHOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Template.
        /// </summary>
        internal static string DEVICE_DATA_TEMPLATE {
            get {
                return ResourceManager.GetString("DEVICE_DATA_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accept.
        /// </summary>
        internal static string GENERICS_ACCEPT {
            get {
                return ResourceManager.GetString("GENERICS_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Address.
        /// </summary>
        internal static string GENERICS_ADDRESS {
            get {
                return ResourceManager.GetString("GENERICS_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string GENERICS_CANCEL {
            get {
                return ResourceManager.GetString("GENERICS_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clear.
        /// </summary>
        internal static string GENERICS_CLEAR {
            get {
                return ResourceManager.GetString("GENERICS_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Comment.
        /// </summary>
        internal static string GENERICS_COMMENT {
            get {
                return ResourceManager.GetString("GENERICS_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configuration.
        /// </summary>
        internal static string GENERICS_CONFIGURATION {
            get {
                return ResourceManager.GetString("GENERICS_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set / to disable..
        /// </summary>
        internal static string GENERICS_DESCR_SET_SLASH_TO_DISABLE {
            get {
                return ResourceManager.GetString("GENERICS_DESCR_SET_SLASH_TO_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File.
        /// </summary>
        internal static string GENERICS_FILE {
            get {
                return ResourceManager.GetString("GENERICS_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a HMI.
        /// </summary>
        internal static string GENERICS_HMI {
            get {
                return ResourceManager.GetString("GENERICS_HMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Left.
        /// </summary>
        internal static string GENERICS_LEFT {
            get {
                return ResourceManager.GetString("GENERICS_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Load.
        /// </summary>
        internal static string GENERICS_LOAD {
            get {
                return ResourceManager.GetString("GENERICS_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name.
        /// </summary>
        internal static string GENERICS_NAME {
            get {
                return ResourceManager.GetString("GENERICS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Number.
        /// </summary>
        internal static string GENERICS_NUMBER {
            get {
                return ResourceManager.GetString("GENERICS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Program.
        /// </summary>
        internal static string GENERICS_PROGRAM {
            get {
                return ResourceManager.GetString("GENERICS_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Quantity.
        /// </summary>
        internal static string GENERICS_QUANTITY {
            get {
                return ResourceManager.GetString("GENERICS_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Right.
        /// </summary>
        internal static string GENERICS_RIGHT {
            get {
                return ResourceManager.GetString("GENERICS_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        internal static string GENERICS_SAVE {
            get {
                return ResourceManager.GetString("GENERICS_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SaveAs.
        /// </summary>
        internal static string GENERICS_SAVE_AS {
            get {
                return ResourceManager.GetString("GENERICS_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        internal static string GENERICS_SETTINGS {
            get {
                return ResourceManager.GetString("GENERICS_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Setup.
        /// </summary>
        internal static string GENERICS_SETUP {
            get {
                return ResourceManager.GetString("GENERICS_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type.
        /// </summary>
        internal static string GENERICS_TYPE {
            get {
                return ResourceManager.GetString("GENERICS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value.
        /// </summary>
        internal static string GENERICS_VALUE {
            get {
                return ResourceManager.GetString("GENERICS_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Variable.
        /// </summary>
        internal static string GENERICS_VARIABLE {
            get {
                return ResourceManager.GetString("GENERICS_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Find.
        /// </summary>
        internal static string GRID_FIND_FIND_BUTTON {
            get {
                return ResourceManager.GetString("GRID_FIND_FIND_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grid - Find and Replace.
        /// </summary>
        internal static string GRID_FIND_FORM_NAME {
            get {
                return ResourceManager.GetString("GRID_FIND_FORM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Match Case.
        /// </summary>
        internal static string GRID_FIND_MATCH_CASE_CHECKBOX {
            get {
                return ResourceManager.GetString("GRID_FIND_MATCH_CASE_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ReplaceAll.
        /// </summary>
        internal static string GRID_FIND_REPLACE_ALL_BUTTON {
            get {
                return ResourceManager.GetString("GRID_FIND_REPLACE_ALL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search completed. Replaced {count} values..
        /// </summary>
        internal static string GRID_FIND_REPLACE_ALL_COMPLETED {
            get {
                return ResourceManager.GetString("GRID_FIND_REPLACE_ALL_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Replace.
        /// </summary>
        internal static string GRID_FIND_REPLACE_BUTTON {
            get {
                return ResourceManager.GetString("GRID_FIND_REPLACE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search completed.
        /// </summary>
        internal static string GRID_FIND_SEARCH_COMPLETED {
            get {
                return ResourceManager.GetString("GRID_FIND_SEARCH_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Format Code.
        /// </summary>
        internal static string GRID_SCRIPT_AUTO_FORMAT {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_AUTO_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Execute on all lines.
        /// </summary>
        internal static string GRID_SCRIPT_EXECUTE_ALL {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_EXECUTE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Execute on selected line.
        /// </summary>
        internal static string GRID_SCRIPT_EXECUTE_ONE_LINE {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_EXECUTE_ONE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Javascript Expression.
        /// </summary>
        internal static string GRID_SCRIPT_JS_EXPRESSION {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_JS_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a JSON Context.
        /// </summary>
        internal static string GRID_SCRIPT_JSON_CONTEXT {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_JSON_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open Javascript executed.
        /// </summary>
        internal static string GRID_SCRIPT_OPEN_JAVASCRIPT_CONTEXT {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_OPEN_JAVASCRIPT_CONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Variables: .
        /// </summary>
        internal static string GRID_SCRIPT_VARIABLES {
            get {
                return ResourceManager.GetString("GRID_SCRIPT_VARIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Address.
        /// </summary>
        internal static string IO_DATA_ADDRESS {
            get {
                return ResourceManager.GetString("IO_DATA_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Comment.
        /// </summary>
        internal static string IO_DATA_COMMENT {
            get {
                return ResourceManager.GetString("IO_DATA_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IO Tag.
        /// </summary>
        internal static string IO_DATA_IO_NAME {
            get {
                return ResourceManager.GetString("IO_DATA_IO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merker Address.
        /// </summary>
        internal static string IO_DATA_MERKER_ADDRESS {
            get {
                return ResourceManager.GetString("IO_DATA_MERKER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Negated.
        /// </summary>
        internal static string IO_DATA_NEGATED {
            get {
                return ResourceManager.GetString("IO_DATA_NEGATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Variable.
        /// </summary>
        internal static string IO_DATA_VARIABLE {
            get {
                return ResourceManager.GetString("IO_DATA_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alias DB.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_DB {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alias Table.
        /// </summary>
        internal static string IO_GEN_CONFIG_ALIAS_TABLE {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_ALIAS_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alias FC.
        /// </summary>
        internal static string IO_GEN_CONFIG_FC {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IN/OUT Table.
        /// </summary>
        internal static string IO_GEN_CONFIG_IO_TABLE {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_IO_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Segment Name.
        /// </summary>
        internal static string IO_GEN_CONFIG_SEGMENT {
            get {
                return ResourceManager.GetString("IO_GEN_CONFIG_SEGMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import Excel.
        /// </summary>
        internal static string IO_GEN_EXCELIMPORT_IMPORT {
            get {
                return ResourceManager.GetString("IO_GEN_EXCELIMPORT_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import/Export.
        /// </summary>
        internal static string IO_GEN_FORM_IMPEXP {
            get {
                return ResourceManager.GetString("IO_GEN_FORM_IMPEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Export XML.
        /// </summary>
        internal static string IO_GEN_FORM_IMPEXP_EXPORT_XML {
            get {
                return ResourceManager.GetString("IO_GEN_FORM_IMPEXP_EXPORT_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import Excel.
        /// </summary>
        internal static string IO_GEN_FORM_IMPEXP_IMPORT_EXCEL {
            get {
                return ResourceManager.GetString("IO_GEN_FORM_IMPEXP_IMPORT_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import IO from Tag table.
        /// </summary>
        internal static string IO_GEN_FORM_IMPEXP_IMPORT_IO {
            get {
                return ResourceManager.GetString("IO_GEN_FORM_IMPEXP_IMPORT_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import Suggestions From DB or Tag table.
        /// </summary>
        internal static string IO_GEN_FORM_IMPEXP_IMPORT_SUGGESTION {
            get {
                return ResourceManager.GetString("IO_GEN_FORM_IMPEXP_IMPORT_SUGGESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Input/Output alias generator. Project file: {file_path}.
        /// </summary>
        internal static string IO_GEN_FORM_NAME {
            get {
                return ResourceManager.GetString("IO_GEN_FORM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bit.
        /// </summary>
        internal static string IO_GROUPING_TYPE_BIT {
            get {
                return ResourceManager.GetString("IO_GROUPING_TYPE_BIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Byte.
        /// </summary>
        internal static string IO_GROUPING_TYPE_BYTE {
            get {
                return ResourceManager.GetString("IO_GROUPING_TYPE_BYTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DB.
        /// </summary>
        internal static string IO_MEMORY_TYPE_DB {
            get {
                return ResourceManager.GetString("IO_MEMORY_TYPE_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Merker.
        /// </summary>
        internal static string IO_MEMORY_TYPE_MERKER {
            get {
                return ResourceManager.GetString("IO_MEMORY_TYPE_MERKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Input: Default address.
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_DB_INPUT_DEFAULT {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_DB_INPUT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name to give to the generated DB.
        ///Placeholder: &lt;placeholder&gt;..
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_DB_NAME_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_DB_NAME_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Number to give to the generated DB. Set to -1 to use auto numeration.
        ///Placeholder: &lt;placeholder&gt;.
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_DB_NUMBER_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_DB_NUMBER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Output: Default address.
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_DB_OUTPUT_DEFAULT {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_DB_OUTPUT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Default Value.
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_TABLE_INOUT_DEFAULT {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_TABLE_INOUT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start Address.
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_TABLE_INOUT_START_ADDRESS {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_TABLE_INOUT_START_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Input Merker: Default name.
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_TABLE_INPUT_DEFAULT_NAME {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_TABLE_INPUT_DEFAULT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Input Merker: Start number.
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_TABLE_INPUT_START_NUMBER {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_TABLE_INPUT_START_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name to give to the table hosting Merker tags (%M).
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_TABLE_NAME_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_TABLE_NAME_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Output Merker: Default name.
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_TABLE_OUTPUT_DEFAULT_NAME {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_TABLE_OUTPUT_DEFAULT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Output Merker: Start number.
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_TABLE_OUTPUT_START_NUMBER {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_TABLE_OUTPUT_START_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New every n° bit.
        /// </summary>
        internal static string IO_SETTINGS_ALIAS_TABLE_SPLIT_EVERY {
            get {
                return ResourceManager.GetString("IO_SETTINGS_ALIAS_TABLE_SPLIT_EVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Excel Importer.
        /// </summary>
        internal static string IO_SETTINGS_EXCELIMPORT {
            get {
                return ResourceManager.GetString("IO_SETTINGS_EXCELIMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Template to use to fill address column.
        ///Use $ followed by Excel column name for extracting values from imported spreadsheet file (Supported by all values here)..
        /// </summary>
        internal static string IO_SETTINGS_EXCELIMPORT_ADDRESS_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_EXCELIMPORT_ADDRESS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Template to use to fill comment column..
        /// </summary>
        internal static string IO_SETTINGS_EXCELIMPORT_COMMENT_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_EXCELIMPORT_COMMENT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a JS Expressione
        ///for row validation.
        /// </summary>
        internal static string IO_SETTINGS_EXCELIMPORT_EXPRESSION {
            get {
                return ResourceManager.GetString("IO_SETTINGS_EXCELIMPORT_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Javascript expression to decide if the spreadsheet row is valid to be parsed..
        /// </summary>
        internal static string IO_SETTINGS_EXCELIMPORT_EXPRESSION_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_EXCELIMPORT_EXPRESSION_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IO Name.
        /// </summary>
        internal static string IO_SETTINGS_EXCELIMPORT_IO_NAME {
            get {
                return ResourceManager.GetString("IO_SETTINGS_EXCELIMPORT_IO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Template to use to fill io name column..
        /// </summary>
        internal static string IO_SETTINGS_EXCELIMPORT_IO_NAME_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_EXCELIMPORT_IO_NAME_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Starting row.
        /// </summary>
        internal static string IO_SETTINGS_EXCELIMPORT_STARTING_ROW {
            get {
                return ResourceManager.GetString("IO_SETTINGS_EXCELIMPORT_STARTING_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Decideds at which spreadsheet row to start parsing data..
        /// </summary>
        internal static string IO_SETTINGS_EXCELIMPORT_STARTING_ROW_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_EXCELIMPORT_STARTING_ROW_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grouping Type.
        /// </summary>
        internal static string IO_SETTINGS_GROUPING_TYPE {
            get {
                return ResourceManager.GetString("IO_SETTINGS_GROUPING_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Decides how alarms are groupped inside a segments are generated.
        ///Bit=Single IO for each segment.
        ///Byte=Group the whole byte for each segnemt..
        /// </summary>
        internal static string IO_SETTINGS_GROUPING_TYPE_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_GROUPING_TYPE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Default Tag name preset.
        /// </summary>
        internal static string IO_SETTINGS_IO_TABLE_DEFAULT_NAME {
            get {
                return ResourceManager.GetString("IO_SETTINGS_IO_TABLE_DEFAULT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Default name to give to the generated tag..
        /// </summary>
        internal static string IO_SETTINGS_IO_TABLE_DEFAULT_NAME_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_IO_TABLE_DEFAULT_NAME_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name to give to the table hosting IO tags (%I / %Q).
        /// </summary>
        internal static string IO_SETTINGS_IO_TABLE_NAME_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_IO_TABLE_NAME_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New every n° bit.
        /// </summary>
        internal static string IO_SETTINGS_IO_TABLE_SPLIT_EVERY {
            get {
                return ResourceManager.GetString("IO_SETTINGS_IO_TABLE_SPLIT_EVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generate a new xml file after the set number of bits. Big tables takes a lot more time to import..
        /// </summary>
        internal static string IO_SETTINGS_IO_TABLE_SPLIT_EVERY_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_IO_TABLE_SPLIT_EVERY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Memory Type.
        /// </summary>
        internal static string IO_SETTINGS_MEMORY_TYPE {
            get {
                return ResourceManager.GetString("IO_SETTINGS_MEMORY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dicides the type of memory wherealias are generated..
        /// </summary>
        internal static string IO_SETTINGS_MEMORY_TYPE_DESC {
            get {
                return ResourceManager.GetString("IO_SETTINGS_MEMORY_TYPE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bit grouping.
        /// </summary>
        internal static string IO_SETTINGS_SEGMENT_BIT_GROUPING {
            get {
                return ResourceManager.GetString("IO_SETTINGS_SEGMENT_BIT_GROUPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Byte grouping.
        /// </summary>
        internal static string IO_SETTINGS_SEGMENT_BYTE_GROUPING {
            get {
                return ResourceManager.GetString("IO_SETTINGS_SEGMENT_BYTE_GROUPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prompt.
        /// </summary>
        internal static string IO_SUGGESTION_DATA_VALUE {
            get {
                return ResourceManager.GetString("IO_SUGGESTION_DATA_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tia Utilities.
        /// </summary>
        internal static string MAIN_FORM {
            get {
                return ResourceManager.GetString("MAIN_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alarm Generator.
        /// </summary>
        internal static string MAIN_FORM_TOP_ALARM_GENERATOR {
            get {
                return ResourceManager.GetString("MAIN_FORM_TOP_ALARM_GENERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DB Duplication.
        /// </summary>
        internal static string MAIN_FORM_TOP_DB_DUPLICATION {
            get {
                return ResourceManager.GetString("MAIN_FORM_TOP_DB_DUPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alias Generator.
        /// </summary>
        internal static string MAIN_FORM_TOP_IO_GENERATION {
            get {
                return ResourceManager.GetString("MAIN_FORM_TOP_IO_GENERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Auto-Save (s).
        /// </summary>
        internal static string PROGRAM_SETTINGS_AUTO_SAVE {
            get {
                return ResourceManager.GetString("PROGRAM_SETTINGS_AUTO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grid Preferences.
        /// </summary>
        internal static string PROGRAM_SETTINGS_GRID_PREFERENCES {
            get {
                return ResourceManager.GetString("PROGRAM_SETTINGS_GRID_PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Colors.
        /// </summary>
        internal static string PROGRAM_SETTINGS_GRID_PREFERENCES_COLORS {
            get {
                return ResourceManager.GetString("PROGRAM_SETTINGS_GRID_PREFERENCES_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Drag triangle.
        /// </summary>
        internal static string PROGRAM_SETTINGS_GRID_PREFERENCES_COLORS_DRAG_TRIANGLE_COLOR {
            get {
                return ResourceManager.GetString("PROGRAM_SETTINGS_GRID_PREFERENCES_COLORS_DRAG_TRIANGLE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dragged cell background.
        /// </summary>
        internal static string PROGRAM_SETTINGS_GRID_PREFERENCES_COLORS_DRAGGED_CELL_BACK {
            get {
                return ResourceManager.GetString("PROGRAM_SETTINGS_GRID_PREFERENCES_COLORS_DRAGGED_CELL_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preview.
        /// </summary>
        internal static string PROGRAM_SETTINGS_GRID_PREFERENCES_COLORS_PREVIEW_FORE {
            get {
                return ResourceManager.GetString("PROGRAM_SETTINGS_GRID_PREFERENCES_COLORS_PREVIEW_FORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selected cell border.
        /// </summary>
        internal static string PROGRAM_SETTINGS_GRID_PREFERENCES_COLORS_SELECTED_CELL_BORDER {
            get {
                return ResourceManager.GetString("PROGRAM_SETTINGS_GRID_PREFERENCES_COLORS_SELECTED_CELL_BORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language.
        /// </summary>
        internal static string PROGRAM_SETTINGS_LANGUAGE {
            get {
                return ResourceManager.GetString("PROGRAM_SETTINGS_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TIA Portal Version.
        /// </summary>
        internal static string PROGRAM_SETTINGS_TIA_VERSION {
            get {
                return ResourceManager.GetString("PROGRAM_SETTINGS_TIA_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open other configuration fast edit.
        /// </summary>
        internal static string SETTINGS_FORM_CONTEXT_MENU_OPEN_OTHER_CONF_FAST_EDIT {
            get {
                return ResourceManager.GetString("SETTINGS_FORM_CONTEXT_MENU_OPEN_OTHER_CONF_FAST_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Transfer values to all others configurations.
        /// </summary>
        internal static string SETTINGS_FORM_CONTEXT_MENU_SET_TO_OTHERS {
            get {
                return ResourceManager.GetString("SETTINGS_FORM_CONTEXT_MENU_SET_TO_OTHERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Support placeholders..
        /// </summary>
        internal static string SETTINGS_FORM_SECTION_HAS_PLACEHOLDER_TOOLTIP {
            get {
                return ResourceManager.GetString("SETTINGS_FORM_SECTION_HAS_PLACEHOLDER_TOOLTIP", resourceCulture);
            }
        }
    }
}
